#pragma line 1 "apint_arith.c" ::: 0
#pragma line 1 "apint_arith.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "apint_arith.c" 2 ::: 194
#pragma line 1 "./apint_arith.h" 1 ::: 287
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 383
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 411
#pragma line 122 "/usr/include/features.h" 3 4 ::: 508
#pragma line 156 "/usr/include/features.h" 3 4 ::: 533
#pragma line 180 "/usr/include/features.h" 3 4 ::: 535
#pragma line 191 "/usr/include/features.h" 3 4 ::: 538
#pragma line 343 "/usr/include/features.h" 3 4 ::: 569
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 573
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 608
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 615
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 638
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 679
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 685
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 703
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 709
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 713
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 715
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 719
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 729
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 782
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 823
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 848
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 872
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 873
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 875
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 877
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 878
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 903
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 914
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 919
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 920
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 921
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 927
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 968
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 971
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 973
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1001
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1003
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1005
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1066
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1073
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1091
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1096
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1107
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1176
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1190
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1193
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1194
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1226
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1242
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1267
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1270
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1275
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1297
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1318
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1321
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1332
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1342
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1344
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1348
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1397
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1398
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1404
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1406
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1426
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1437
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1478
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1508
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1534
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1538
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1553
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1565
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1571
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1573
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1583
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1605
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1621
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1638
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1670
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1716
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1730
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1733
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1809
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1848
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1889
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 2002
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 2065
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2114
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 2125
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2155
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2183
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2215
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2227
#pragma line 96 "./apint_arith.h" 2 ::: 2230
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" 1 ::: 2231
#pragma line 62 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" ::: 2284
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2285
#pragma line 29 "/usr/include/string.h" 3 4 ::: 2306
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2311
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2336
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2339
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2376
#pragma line 124 "/usr/include/string.h" 3 4 ::: 2379
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2416
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 2459
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2481
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2483
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2488
#pragma line 278 "/usr/include/string.h" 3 4 ::: 2491
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2501
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2506
#pragma line 393 "/usr/include/string.h" 3 4 ::: 2527
#pragma line 439 "/usr/include/string.h" 3 4 ::: 2558
#pragma line 484 "/usr/include/string.h" 3 4 ::: 2581
#pragma line 512 "/usr/include/string.h" 3 4 ::: 2587
#pragma line 550 "/usr/include/string.h" 3 4 ::: 2611
#pragma line 63 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" 2 ::: 2637
#pragma line 77 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" ::: 2638
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 2639
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 2697
#pragma line 97 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" ::: 2751
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 2752
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 3791
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 3792
#pragma line 99 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 4819
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" ::: 4820
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 4821
#pragma line 109 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5860
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 5861
#pragma line 110 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 6888
#pragma line 131 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" ::: 6889
#pragma line 147 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" ::: 6892
#pragma line 58 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6894
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 6895
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6948
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6950
#pragma line 129 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6952
#pragma line 143 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6957
#pragma line 156 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6960
#pragma line 192 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6962
#pragma line 358 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6964
#pragma line 59 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6966
#pragma line 85 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 6967
#pragma line 114 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 6969
#pragma line 78 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" 2 ::: 6971
#pragma line 88 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" ::: 6972
#pragma line 97 "./apint_arith.h" 2 ::: 6974
#pragma line 93 "apint_arith.c" 2 ::: 6999
