#pragma line 1 "apint_arith.c" ::: -10
#pragma line 1 "apint_arith.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "apint_arith.c" 2 ::: 184
#pragma line 1 "./apint_arith.h" 1 ::: 277
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 373
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 401
#pragma line 122 "/usr/include/features.h" 3 4 ::: 498
#pragma line 156 "/usr/include/features.h" 3 4 ::: 523
#pragma line 180 "/usr/include/features.h" 3 4 ::: 525
#pragma line 191 "/usr/include/features.h" 3 4 ::: 528
#pragma line 343 "/usr/include/features.h" 3 4 ::: 559
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 563
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 598
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 605
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 628
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 669
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 675
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 693
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 699
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 703
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 705
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 709
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 719
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 772
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 813
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 838
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 862
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 863
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 865
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 867
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 868
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 893
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 904
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 909
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 910
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 911
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 917
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 958
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 961
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 963
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 991
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 993
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 995
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1056
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1063
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1081
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1086
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1097
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1166
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1180
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1183
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1184
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1216
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1232
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1257
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1260
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1265
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1287
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1308
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1311
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1322
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1332
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1334
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1338
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1387
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1388
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1394
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1396
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1416
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1427
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1468
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1498
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1524
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1528
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1543
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1555
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1561
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1563
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1573
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1595
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1611
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1628
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1660
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1706
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1720
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1723
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1799
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1838
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1879
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1992
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 2055
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2104
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 2115
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2145
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2173
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2205
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2217
#pragma line 96 "./apint_arith.h" 2 ::: 2220
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" 1 ::: 2221
#pragma line 62 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" ::: 2274
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2275
#pragma line 29 "/usr/include/string.h" 3 4 ::: 2296
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2301
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2326
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2329
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2366
#pragma line 124 "/usr/include/string.h" 3 4 ::: 2369
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2406
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 2449
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2471
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2473
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2478
#pragma line 278 "/usr/include/string.h" 3 4 ::: 2481
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2491
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2496
#pragma line 393 "/usr/include/string.h" 3 4 ::: 2517
#pragma line 439 "/usr/include/string.h" 3 4 ::: 2548
#pragma line 484 "/usr/include/string.h" 3 4 ::: 2571
#pragma line 512 "/usr/include/string.h" 3 4 ::: 2577
#pragma line 550 "/usr/include/string.h" 3 4 ::: 2601
#pragma line 63 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" 2 ::: 2627
#pragma line 77 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" ::: 2628
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 2629
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 2687
#pragma line 97 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" ::: 2741
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 2742
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 3781
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 3782
#pragma line 99 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 4809
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" ::: 4810
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 4811
#pragma line 109 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5850
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 5851
#pragma line 110 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 6878
#pragma line 131 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" ::: 6879
#pragma line 147 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_dt.h" ::: 6882
#pragma line 58 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6884
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 6885
#pragma line 98 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6938
#pragma line 108 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6940
#pragma line 129 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6942
#pragma line 143 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6947
#pragma line 156 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6950
#pragma line 192 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6952
#pragma line 358 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6954
#pragma line 59 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6956
#pragma line 85 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 6957
#pragma line 114 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_apint.h" ::: 6959
#pragma line 78 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" 2 ::: 6961
#pragma line 88 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/ap_cint.h" ::: 6962
#pragma line 97 "./apint_arith.h" 2 ::: 6964
#pragma line 93 "apint_arith.c" 2 ::: 6989
