// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _pointer_arith_HH_
#define _pointer_arith_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct pointer_arith : public sc_module {
    // Port declarations 15
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > d_req_din;
    sc_in< sc_logic > d_req_full_n;
    sc_out< sc_logic > d_req_write;
    sc_in< sc_logic > d_rsp_empty_n;
    sc_out< sc_logic > d_rsp_read;
    sc_out< sc_lv<32> > d_address;
    sc_in< sc_lv<32> > d_datain;
    sc_out< sc_lv<32> > d_dataout;
    sc_out< sc_lv<32> > d_size;


    // Module declarations
    pointer_arith(sc_module_name name);
    SC_HAS_PROCESS(pointer_arith);

    ~pointer_arith();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<7> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > acc;
    sc_signal< sc_lv<3> > i_1_fu_72_p2;
    sc_signal< sc_lv<3> > i_1_reg_117;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > d_addr_read_reg_129;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > tmp_1_fu_92_p2;
    sc_signal< sc_lv<32> > tmp_1_reg_134;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<3> > i_reg_54;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<64> > p_sum_cast_fu_78_p1;
    sc_signal< sc_lv<64> > tmp_fu_103_p1;
    sc_signal< sc_lv<1> > exitcond_fu_66_p2;
    sc_signal< sc_lv<7> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<7> ap_ST_fsm_state1;
    static const sc_lv<7> ap_ST_fsm_state2;
    static const sc_lv<7> ap_ST_fsm_state3;
    static const sc_lv<7> ap_ST_fsm_state4;
    static const sc_lv<7> ap_ST_fsm_state5;
    static const sc_lv<7> ap_ST_fsm_state6;
    static const sc_lv<7> ap_ST_fsm_state7;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_d_address();
    void thread_d_dataout();
    void thread_d_req_din();
    void thread_d_req_write();
    void thread_d_rsp_read();
    void thread_d_size();
    void thread_exitcond_fu_66_p2();
    void thread_i_1_fu_72_p2();
    void thread_p_sum_cast_fu_78_p1();
    void thread_tmp_1_fu_92_p2();
    void thread_tmp_fu_103_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
