// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module decimate_strm (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        strm_out_V_din,
        strm_out_V_full_n,
        strm_out_V_write,
        strm_in_V_dout,
        strm_in_V_empty_n,
        strm_in_V_read,
        strm_len
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [31:0] strm_out_V_din;
input   strm_out_V_full_n;
output   strm_out_V_write;
input  [31:0] strm_in_V_dout;
input   strm_in_V_empty_n;
output   strm_in_V_read;
input  [13:0] strm_len;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg strm_out_V_write;
reg strm_in_V_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    strm_out_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0_flag00000000;
reg   [0:0] tmp_5_i_reg_252;
reg   [0:0] ap_reg_pp0_iter1_tmp_5_i_reg_252;
reg    strm_in_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] exitcond_flatten_reg_238;
reg   [13:0] indvar_flatten_reg_117;
reg   [2:0] j_i_reg_128;
reg   [33:0] acc_i_reg_139;
wire   [13:0] tmp_8_fu_161_p3;
reg   [13:0] tmp_8_reg_233;
reg    ap_block_state1;
wire   [0:0] exitcond_flatten_fu_169_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_flag00011001;
reg   [0:0] ap_reg_pp0_iter1_exitcond_flatten_reg_238;
wire   [13:0] indvar_flatten_next_fu_174_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_3_i3_fu_180_p2;
reg   [0:0] tmp_3_i3_reg_247;
wire   [0:0] tmp_5_i_fu_194_p2;
wire   [2:0] j_fu_200_p2;
wire   [33:0] acc_fu_217_p2;
reg   [33:0] acc_reg_261;
reg   [31:0] tmp_6_reg_266;
reg    ap_block_pp0_stage0_flag00011011;
reg    ap_condition_pp0_exit_iter0_state2;
reg   [33:0] acc_i_phi_fu_143_p4;
reg    ap_block_pp0_stage0_flag00001001;
wire   [11:0] tmp_7_fu_151_p4;
wire   [2:0] j_i_mid2_fu_186_p3;
wire  signed [33:0] tmp_4_cast_i_fu_213_p1;
wire   [33:0] acc_i_mid2_fu_206_p3;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state2 ^ 1'b1);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_238))) begin
        acc_i_reg_139 <= acc_reg_261;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        acc_i_reg_139 <= 34'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_flatten_fu_169_p2))) begin
        indvar_flatten_reg_117 <= indvar_flatten_next_fu_174_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        indvar_flatten_reg_117 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_flatten_fu_169_p2))) begin
        j_i_reg_128 <= j_fu_200_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        j_i_reg_128 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_238 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        acc_reg_261 <= acc_fu_217_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        ap_reg_pp0_iter1_exitcond_flatten_reg_238 <= exitcond_flatten_reg_238;
        ap_reg_pp0_iter1_tmp_5_i_reg_252 <= tmp_5_i_reg_252;
        exitcond_flatten_reg_238 <= exitcond_flatten_fu_169_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_flatten_fu_169_p2))) begin
        tmp_3_i3_reg_247 <= tmp_3_i3_fu_180_p2;
        tmp_5_i_reg_252 <= tmp_5_i_fu_194_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (tmp_5_i_reg_252 == 1'd1))) begin
        tmp_6_reg_266 <= {{acc_fu_217_p2[33:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        tmp_8_reg_233[13 : 2] <= tmp_8_fu_161_p3[13 : 2];
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_238))) begin
        acc_i_phi_fu_143_p4 = acc_reg_261;
    end else begin
        acc_i_phi_fu_143_p4 = acc_i_reg_139;
    end
end

always @ (*) begin
    if ((1'd1 == exitcond_flatten_fu_169_p2)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_238 == 1'd0))) begin
        strm_in_V_blk_n = strm_in_V_empty_n;
    end else begin
        strm_in_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_238 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        strm_in_V_read = 1'b1;
    end else begin
        strm_in_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (ap_reg_pp0_iter1_tmp_5_i_reg_252 == 1'd1))) begin
        strm_out_V_blk_n = strm_out_V_full_n;
    end else begin
        strm_out_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter2) & (ap_reg_pp0_iter1_tmp_5_i_reg_252 == 1'd1) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        strm_out_V_write = 1'b1;
    end else begin
        strm_out_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'd1 == exitcond_flatten_fu_169_p2) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'd1 == exitcond_flatten_fu_169_p2) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_217_p2 = ($signed(tmp_4_cast_i_fu_213_p1) + $signed(acc_i_mid2_fu_206_p3));

assign acc_i_mid2_fu_206_p3 = ((tmp_3_i3_reg_247[0:0] === 1'b1) ? 34'd0 : acc_i_phi_fu_143_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_flag00001001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_238 == 1'd0) & (1'b0 == strm_in_V_empty_n)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_reg_pp0_iter1_tmp_5_i_reg_252 == 1'd1) & (1'b0 == strm_out_V_full_n)));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_238 == 1'd0) & (1'b0 == strm_in_V_empty_n)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_reg_pp0_iter1_tmp_5_i_reg_252 == 1'd1) & (1'b0 == strm_out_V_full_n)));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011011 = (((1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_238 == 1'd0) & (1'b0 == strm_in_V_empty_n)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (ap_reg_pp0_iter1_tmp_5_i_reg_252 == 1'd1) & (1'b0 == strm_out_V_full_n)));
end

always @ (*) begin
    ap_block_state1 = ((1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((exitcond_flatten_reg_238 == 1'd0) & (1'b0 == strm_in_V_empty_n));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((ap_reg_pp0_iter1_tmp_5_i_reg_252 == 1'd1) & (1'b0 == strm_out_V_full_n));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond_flatten_fu_169_p2 = ((indvar_flatten_reg_117 == tmp_8_reg_233) ? 1'b1 : 1'b0);

assign indvar_flatten_next_fu_174_p2 = (indvar_flatten_reg_117 + 14'd1);

assign j_fu_200_p2 = (j_i_mid2_fu_186_p3 + 3'd1);

assign j_i_mid2_fu_186_p3 = ((tmp_3_i3_fu_180_p2[0:0] === 1'b1) ? 3'd0 : j_i_reg_128);

assign strm_out_V_din = tmp_6_reg_266;

assign tmp_3_i3_fu_180_p2 = ((j_i_reg_128 == 3'd4) ? 1'b1 : 1'b0);

assign tmp_4_cast_i_fu_213_p1 = $signed(strm_in_V_dout);

assign tmp_5_i_fu_194_p2 = ((j_i_mid2_fu_186_p3 == 3'd3) ? 1'b1 : 1'b0);

assign tmp_7_fu_151_p4 = {{strm_len[13:2]}};

assign tmp_8_fu_161_p3 = {{tmp_7_fu_151_p4}, {2'd0}};

always @ (posedge ap_clk) begin
    tmp_8_reg_233[1:0] <= 2'b00;
end

endmodule //decimate_strm
