// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "apint_arith.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic apint_arith::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic apint_arith::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<37> apint_arith::ap_ST_fsm_state1 = "1";
const sc_lv<37> apint_arith::ap_ST_fsm_state2 = "10";
const sc_lv<37> apint_arith::ap_ST_fsm_state3 = "100";
const sc_lv<37> apint_arith::ap_ST_fsm_state4 = "1000";
const sc_lv<37> apint_arith::ap_ST_fsm_state5 = "10000";
const sc_lv<37> apint_arith::ap_ST_fsm_state6 = "100000";
const sc_lv<37> apint_arith::ap_ST_fsm_state7 = "1000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state8 = "10000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state9 = "100000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state10 = "1000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state11 = "10000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state12 = "100000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<37> apint_arith::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<32> apint_arith::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> apint_arith::ap_const_lv32_B = "1011";
const sc_lv<32> apint_arith::ap_const_lv32_D = "1101";
const sc_lv<32> apint_arith::ap_const_lv32_24 = "100100";
const bool apint_arith::ap_const_boolean_1 = true;

apint_arith::apint_arith(sc_module_name name) : sc_module(name), mVcdFile(0) {
    apint_arith_srem_bkb_U1 = new apint_arith_srem_bkb<1,37,33,6,6>("apint_arith_srem_bkb_U1");
    apint_arith_srem_bkb_U1->clk(ap_clk);
    apint_arith_srem_bkb_U1->reset(ap_rst);
    apint_arith_srem_bkb_U1->start(grp_fu_94_ap_start);
    apint_arith_srem_bkb_U1->done(grp_fu_94_ap_done);
    apint_arith_srem_bkb_U1->din0(inD);
    apint_arith_srem_bkb_U1->din1(inA);
    apint_arith_srem_bkb_U1->ce(ap_var_for_const0);
    apint_arith_srem_bkb_U1->dout(grp_fu_94_p2);
    apint_arith_sdiv_cud_U2 = new apint_arith_sdiv_cud<1,26,22,6,22>("apint_arith_sdiv_cud_U2");
    apint_arith_sdiv_cud_U2->clk(ap_clk);
    apint_arith_sdiv_cud_U2->reset(ap_rst);
    apint_arith_sdiv_cud_U2->start(grp_fu_124_ap_start);
    apint_arith_sdiv_cud_U2->done(grp_fu_124_ap_done);
    apint_arith_sdiv_cud_U2->din0(inC);
    apint_arith_sdiv_cud_U2->din1(inA);
    apint_arith_sdiv_cud_U2->ce(ap_var_for_const0);
    apint_arith_sdiv_cud_U2->dout(grp_fu_124_p2);
    apint_arith_mul_mdEe_U3 = new apint_arith_mul_mdEe<1,3,12,6,18>("apint_arith_mul_mdEe_U3");
    apint_arith_mul_mdEe_U3->clk(ap_clk);
    apint_arith_mul_mdEe_U3->reset(ap_rst);
    apint_arith_mul_mdEe_U3->din0(inB);
    apint_arith_mul_mdEe_U3->din1(inA);
    apint_arith_mul_mdEe_U3->ce(ap_var_for_const0);
    apint_arith_mul_mdEe_U3->dout(grp_fu_136_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_grp_fu_124_ap_start);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_grp_fu_94_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_out1);
    sensitive << ( grp_fu_136_p2 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_out1_ap_vld);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_out2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_3_fu_107_p1 );
    sensitive << ( tmp_4_fu_111_p1 );

    SC_METHOD(thread_out2_ap_vld);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_out3);
    sensitive << ( grp_fu_124_p2 );
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_out3_ap_vld);
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_out4);
    sensitive << ( ap_CS_fsm_state37 );
    sensitive << ( grp_fu_94_p2 );

    SC_METHOD(thread_out4_ap_vld);
    sensitive << ( ap_CS_fsm_state37 );

    SC_METHOD(thread_tmp_3_fu_107_p1);
    sensitive << ( inB );

    SC_METHOD(thread_tmp_4_fu_111_p1);
    sensitive << ( inA );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "apint_arith_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, inA, "(port)inA");
    sc_trace(mVcdFile, inB, "(port)inB");
    sc_trace(mVcdFile, inC, "(port)inC");
    sc_trace(mVcdFile, inD, "(port)inD");
    sc_trace(mVcdFile, out1, "(port)out1");
    sc_trace(mVcdFile, out1_ap_vld, "(port)out1_ap_vld");
    sc_trace(mVcdFile, out2, "(port)out2");
    sc_trace(mVcdFile, out2_ap_vld, "(port)out2_ap_vld");
    sc_trace(mVcdFile, out3, "(port)out3");
    sc_trace(mVcdFile, out3_ap_vld, "(port)out3_ap_vld");
    sc_trace(mVcdFile, out4, "(port)out4");
    sc_trace(mVcdFile, out4_ap_vld, "(port)out4_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_fu_136_p2, "grp_fu_136_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, grp_fu_124_p2, "grp_fu_124_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, tmp_3_fu_107_p1, "tmp_3_fu_107_p1");
    sc_trace(mVcdFile, tmp_4_fu_111_p1, "tmp_4_fu_111_p1");
    sc_trace(mVcdFile, grp_fu_94_p2, "grp_fu_94_p2");
    sc_trace(mVcdFile, grp_fu_94_ap_start, "grp_fu_94_ap_start");
    sc_trace(mVcdFile, grp_fu_94_ap_done, "grp_fu_94_ap_done");
    sc_trace(mVcdFile, grp_fu_124_ap_start, "grp_fu_124_ap_start");
    sc_trace(mVcdFile, grp_fu_124_ap_done, "grp_fu_124_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("apint_arith.hdltvin.dat");
    mHdltvoutHandle.open("apint_arith.hdltvout.dat");
}

apint_arith::~apint_arith() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete apint_arith_srem_bkb_U1;
    delete apint_arith_sdiv_cud_U2;
    delete apint_arith_mul_mdEe_U3;
}

void apint_arith::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void apint_arith::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
}

void apint_arith::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void apint_arith::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void apint_arith::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void apint_arith::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read()[36];
}

void apint_arith::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void apint_arith::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void apint_arith::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void apint_arith::thread_grp_fu_124_ap_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        grp_fu_124_ap_start = ap_const_logic_1;
    } else {
        grp_fu_124_ap_start = ap_const_logic_0;
    }
}

void apint_arith::thread_grp_fu_94_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        grp_fu_94_ap_start = ap_const_logic_1;
    } else {
        grp_fu_94_ap_start = ap_const_logic_0;
    }
}

void apint_arith::thread_out1() {
    out1 = grp_fu_136_p2.read();
}

void apint_arith::thread_out1_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        out1_ap_vld = ap_const_logic_1;
    } else {
        out1_ap_vld = ap_const_logic_0;
    }
}

void apint_arith::thread_out2() {
    out2 = (!tmp_3_fu_107_p1.read().is_01() || !tmp_4_fu_111_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(tmp_3_fu_107_p1.read()) + sc_bigint<13>(tmp_4_fu_111_p1.read()));
}

void apint_arith::thread_out2_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        out2_ap_vld = ap_const_logic_1;
    } else {
        out2_ap_vld = ap_const_logic_0;
    }
}

void apint_arith::thread_out3() {
    out3 = grp_fu_124_p2.read();
}

void apint_arith::thread_out3_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        out3_ap_vld = ap_const_logic_1;
    } else {
        out3_ap_vld = ap_const_logic_0;
    }
}

void apint_arith::thread_out4() {
    out4 = grp_fu_94_p2.read().range(6-1, 0);
}

void apint_arith::thread_out4_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        out4_ap_vld = ap_const_logic_1;
    } else {
        out4_ap_vld = ap_const_logic_0;
    }
}

void apint_arith::thread_tmp_3_fu_107_p1() {
    tmp_3_fu_107_p1 = esl_sext<13,12>(inB.read());
}

void apint_arith::thread_tmp_4_fu_111_p1() {
    tmp_4_fu_111_p1 = esl_sext<13,6>(inA.read());
}

void apint_arith::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

void apint_arith::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inA\" :  \"" << inA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inB\" :  \"" << inB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inC\" :  \"" << inC.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inD\" :  \"" << inD.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out1\" :  \"" << out1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out1_ap_vld\" :  \"" << out1_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out2\" :  \"" << out2.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out2_ap_vld\" :  \"" << out2_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out3\" :  \"" << out3.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out3_ap_vld\" :  \"" << out3_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out4\" :  \"" << out4.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out4_ap_vld\" :  \"" << out4_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

